# Generated by Django 5.2 on 2025-07-02 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(default='#007bff', help_text='Code couleur hexadécimal pour les graphiques', max_length=7, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Fichier')),
                ('file_type', models.CharField(choices=[('excel', 'Excel (.xlsx, .xls)'), ('csv', 'CSV (.csv)')], max_length=10, verbose_name='Type de fichier')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'upload")),
                ('processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Fichier uploadé',
                'verbose_name_plural': 'Fichiers uploadés',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('entry_type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense')], max_length=10, verbose_name='Type')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='compta.uploadedfile', verbose_name='Fichier source')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
