# Generated by Django 5.2 on 2025-07-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='financialentry',
            name='category',
        ),
    ]
