# Generated by Django 5.2 on 2025-07-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0002_remove_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Fichier importé', 'verbose_name_plural': 'Fichiers importés'},
        ),
    ]
